spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  docker:
    compose:
      file: docker-compose.yml
      enabled: true